/// <reference types="react" />
declare type SVGProps = React.SVGProps<SVGSVGElement>;
export declare function USD_ICON(props: SVGProps): JSX.Element;
export declare function EUR_ICON(props: SVGProps): JSX.Element;
export declare function RUB_ICON(props: SVGProps): JSX.Element;
export declare function INR_ICON(props: SVGProps): JSX.Element;
export declare function GBP_ICON(props: SVGProps): JSX.Element;
export declare function JPY_ICON(props: SVGProps): JSX.Element;
export declare function VND_ICON(props: SVGProps): JSX.Element;
export declare function SGD_ICON(props: SVGProps): JSX.Element;
export declare function BRL_ICON(props: SVGProps): JSX.Element;
export declare function HKD_ICON(props: SVGProps): JSX.Element;
export declare function CAD_ICON(props: SVGProps): JSX.Element;
export declare function IDR_ICON(props: SVGProps): JSX.Element;
export declare function TRY_ICON(props: SVGProps): JSX.Element;
export declare function NGN_ICON(props: SVGProps): JSX.Element;
export declare function AUD_ICON(props: SVGProps): JSX.Element;
export declare function PKR_ICON(props: SVGProps): JSX.Element;
export declare function UAH_ICON(props: SVGProps): JSX.Element;
export declare function THB_ICON(props: SVGProps): JSX.Element;
export {};
