import { ChainId, Currency, NativeCurrency, Token } from "@uniswap/sdk-core";
export declare const NATIVE_CHAIN_ID = "NATIVE";
export declare const DEFAULT_ERC20_DECIMALS = 18;
export declare const USDC_MAINNET: Token;
export declare const USDC_OPTIMISM: Token;
export declare const BRIDGED_USDC_ARBITRUM: Token;
export declare const USDC_ARBITRUM: Token;
export declare const USDC_ARBITRUM_GOERLI: Token;
export declare const USDC_POLYGON: Token;
export declare const PORTAL_USDC_CELO: Token;
export declare const USDC_BASE: Token;
export declare const DAI: Token;
export declare const DAI_ARBITRUM_ONE: Token;
export declare const DAI_OPTIMISM: Token;
export declare const MATIC: Token;
export declare const DAI_POLYGON: Token;
export declare const USDT_POLYGON: Token;
export declare const WBTC_POLYGON: Token;
export declare const USDT: Token;
export declare const USDT_ARBITRUM_ONE: Token;
export declare const USDT_OPTIMISM: Token;
export declare const WBTC: Token;
export declare const WBTC_ARBITRUM_ONE: Token;
export declare const WBTC_OPTIMISM: Token;
export declare const WETH_POLYGON_MUMBAI: Token;
export declare const WETH_POLYGON: Token;
export declare const CUSD_CELO: Token;
export declare const CEUR_CELO: Token;
export declare const PORTAL_ETH_CELO: Token;
export declare const WBTC_CELO: Token;
export declare const CUSD_CELO_ALFAJORES: Token;
export declare const CEUR_CELO_ALFAJORES: Token;
export declare const USDC_BSC: Token;
export declare const USDT_BSC: Token;
export declare const ETH_BSC: Token;
export declare const BTC_BSC: Token;
export declare const BUSD_BSC: Token;
export declare const DAI_BSC: Token;
export declare const USDC_AVALANCHE: Token;
export declare const USDT_AVALANCHE: Token;
export declare const WETH_AVALANCHE: Token;
export declare const DAI_AVALANCHE: Token;
export declare const UNI: {
    [chainId: number]: Token;
};
export declare const ARB: Token;
export declare const OP: Token;
export declare const LDO: Token;
export declare const WRAPPED_NATIVE_CURRENCY: {
    [chainId: number]: Token | undefined;
};
export declare function isCelo(chainId: number): chainId is ChainId.CELO | ChainId.CELO_ALFAJORES;
export declare function isMatic(chainId: number): chainId is ChainId.POLYGON | ChainId.POLYGON_MUMBAI;
export declare function isBsc(chainId: number): chainId is ChainId.BNB;
export declare function isAvalanche(chainId: number): chainId is ChainId.AVALANCHE;
export declare function nativeOnChain(chainId: number): NativeCurrency | Token;
export declare function getSwapCurrencyId(currency: Currency): string;
export declare const TOKEN_SHORTHANDS: {
    [shorthand: string]: {
        [chainId in ChainId]?: string;
    };
};
