import { ChainId } from "@uniswap/sdk-core";
import { TransactionStatus } from "graphql/data/__generated__/types-and-hooks";
import { ChainTokenMap } from "hooks/Tokens";
import { SignatureDetails } from "state/signatures/types";
import { TransactionDetails } from "state/transactions/types";
import { useFormatter } from "utils/formatNumbers";
import { Activity, ActivityMap } from "./types";
type FormatNumberFunctionType = ReturnType<typeof useFormatter>["formatNumber"];
export declare function getTransactionStatus(details: TransactionDetails): TransactionStatus;
export declare function transactionToActivity(details: TransactionDetails, chainId: ChainId, tokens: ChainTokenMap, formatNumber: FormatNumberFunctionType): Activity | undefined;
export declare function signatureToActivity(signature: SignatureDetails, tokens: ChainTokenMap, formatNumber: FormatNumberFunctionType): Activity | undefined;
export declare function useLocalActivities(account: string): ActivityMap;
export {};
