import { AppState } from "state/reducer";
import { ApplicationModal, PopupContent } from "./reducer";
export declare function useModalIsOpen(modal: ApplicationModal): boolean;
export declare function useFiatOnrampAvailability(shouldCheck: boolean, callback?: () => void): {
    available: boolean;
    availabilityChecked: boolean;
    loading: boolean;
    error: string | null;
};
export declare function useToggleModal(modal: ApplicationModal): () => void;
export declare function useCloseModal(): (modalToClose?: ApplicationModal) => void;
export declare function useOpenModal(modal: ApplicationModal): () => void;
export declare function useToggleSettingsMenu(): () => void;
export declare function useShowClaimPopup(): boolean;
export declare function useToggleShowClaimPopup(): () => void;
export declare function useToggleSelfClaimModal(): () => void;
export declare function useToggleDelegateModal(): () => void;
export declare function useToggleVoteModal(): () => void;
export declare function useToggleQueueModal(): () => void;
export declare function useToggleExecuteModal(): () => void;
export declare function useTogglePrivacyPolicy(): () => void;
export declare function useToggleFeatureFlags(): () => void;
export declare function useAddPopup(): (content: PopupContent, key?: string, removeAfterMs?: number) => void;
export declare function useRemovePopup(): (key: string) => void;
export declare function useActivePopups(): AppState["application"]["popupList"];
