import React from "react";
type SVGProps = React.SVGProps<SVGSVGElement> & {
    fill?: string;
    height?: string | number;
    width?: string | number;
    gradientId?: string;
};
export declare const UniIcon: (props: SVGProps) => JSX.Element;
export declare const ChevronUpIcon: ({ secondaryColor, secondaryWidth, secondaryHeight, ...props }: React.SVGProps<SVGSVGElement> & {
    fill?: string | undefined;
    height?: string | number | undefined;
    width?: string | number | undefined;
    gradientId?: string | undefined;
} & {
    secondaryWidth?: string | undefined;
    secondaryHeight?: string | undefined;
    secondaryColor?: string | undefined;
}) => JSX.Element;
export declare const BackArrowIcon: (props: SVGProps) => JSX.Element;
export declare const VerifiedIcon: (props: SVGProps) => JSX.Element;
export declare const PoolIcon: ({ width, height, ...props }: SVGProps) => JSX.Element;
export declare const XMarkIcon: (props: SVGProps) => JSX.Element;
export declare const ExternalIcon: (props: SVGProps) => JSX.Element;
export declare const InstagramIcon: (props: SVGProps) => JSX.Element;
export declare const EllipsisIcon: (props: SVGProps) => JSX.Element;
export declare const LightningBoltIcon: (props: SVGProps) => JSX.Element;
export declare const SweepIcon: (props: SVGProps) => JSX.Element;
export declare const CrossIcon: (props: SVGProps) => JSX.Element;
export declare const ArrowsIcon: () => JSX.Element;
export declare const ReversedArrowsIcon: () => JSX.Element;
export declare const RarityVerifiedIcon: () => JSX.Element;
export declare const BrokenLinkIcon: (props: SVGProps) => JSX.Element;
export declare const RowsCollpsedIcon: () => JSX.Element;
export declare const RowsExpandedIcon: () => JSX.Element;
export declare const ClockIcon: () => JSX.Element;
export declare const ApprovedCheckmarkIcon: (props: SVGProps) => JSX.Element;
export declare const FilterIcon: (props: SVGProps) => JSX.Element;
export declare const NavMagnifyingGlassIcon: () => JSX.Element;
export declare const BagIcon: (props: SVGProps) => JSX.Element;
export declare const HundredsOverflowIcon: () => JSX.Element;
export declare const TagIcon: (props: SVGProps) => JSX.Element;
export declare const BarChartIcon: (props: SVGProps) => JSX.Element;
export declare const DiscordIcon: (props: SVGProps) => JSX.Element;
export declare const TwitterIcon: (props: SVGProps) => JSX.Element;
export declare const DiscordIconMenu: (props: SVGProps) => JSX.Element;
export declare const TwitterIconMenu: (props: SVGProps) => JSX.Element;
export declare const GithubIconMenu: (props: SVGProps) => JSX.Element;
export declare const CheckMarkIcon: (props: SVGProps) => JSX.Element;
export declare const GovernanceIcon: (props: SVGProps) => JSX.Element;
export declare const ChevronLeftIcon: (props: SVGProps) => JSX.Element;
export declare const ChevronRightIcon: import("styled-components").StyledComponent<(props: SVGProps) => JSX.Element, import("styled-components").DefaultTheme, {}, never>;
export declare const TrendingArrow: (props: SVGProps) => JSX.Element;
export declare const ActivityListingIcon: (props: SVGProps) => JSX.Element;
export declare const ActivitySaleIcon: (props: SVGProps) => JSX.Element;
export declare const ActivityTransferIcon: (props: SVGProps) => JSX.Element;
export declare const ActivityExternalLinkIcon: () => JSX.Element;
export declare const LargeTagIcon: (props: SVGProps) => JSX.Element;
export declare const CircularCloseIcon: (props: SVGProps) => JSX.Element;
export declare const SquareArrowDownIcon: (props: SVGProps) => JSX.Element;
export declare const SquareArrowUpIcon: (props: SVGProps) => JSX.Element;
export declare const CloseTimerIcon: (props: SVGProps) => JSX.Element;
export declare const ChevronDownBagIcon: (props: SVGProps) => JSX.Element;
export declare const ChevronUpBagIcon: (props: SVGProps) => JSX.Element;
export declare const BagCloseIcon: (props: SVGProps) => JSX.Element;
export declare const CancelListingIcon: (props: SVGProps) => JSX.Element;
export declare const ListingModalWindowActive: (props: SVGProps) => JSX.Element;
export declare const ListingModalWindowClosed: (props: SVGProps) => JSX.Element;
export declare const OpenSeaMarketplaceIcon: (props: SVGProps) => JSX.Element;
export declare const CollectionSelectedAssetIcon: (props: SVGProps) => JSX.Element;
export declare const Nft20Icon: (props: SVGProps) => JSX.Element;
export declare const NftXIcon: (props: SVGProps) => JSX.Element;
export declare const X2y2Icon: (props: SVGProps) => JSX.Element;
export declare const SudoSwapIcon: (props: SVGProps) => JSX.Element;
export declare const LooksRareIcon: (props: SVGProps) => JSX.Element;
export declare const LarvaLabsMarketplaceIcon: (props: SVGProps) => JSX.Element;
export declare const SquareOpenSeaMarketplaceIcon: (props: SVGProps) => JSX.Element;
export declare const SquareLooksRareMarketplaceIcon: (props: SVGProps) => JSX.Element;
export declare const SquareLooksX2Y2MarketplaceIcon: ({ gradientId, ...rest }: SVGProps) => JSX.Element;
export declare const SquareLooksBlurMarketplaceIcon: (props: SVGProps) => JSX.Element;
export declare const SquareSudoSwapMarketplaceIcon: (props: SVGProps) => JSX.Element;
export declare const SquareNftXMarketplaceIcon: ({ gradientId, ...rest }: SVGProps) => JSX.Element;
export declare const SquareGemMarketplaceIcon: ({ gradientId, ...rest }: SVGProps) => JSX.Element;
export declare const SquareZoraMarketplaceIcon: ({ gradientId, ...rest }: SVGProps) => JSX.Element;
export declare const SquareEnsVisionMarketplaceIcon: ({ gradientId, ...rest }: SVGProps) => JSX.Element;
export declare const SquareCryptopunksMarketplaceIcon: (props: SVGProps) => JSX.Element;
export declare const SquareRaribleMarketplaceIcon: (props: SVGProps) => JSX.Element;
export declare const SquareFoundationMarketplaceIcon: (props: SVGProps) => JSX.Element;
export declare const SquareNft20MarketplaceIcon: (props: SVGProps) => JSX.Element;
export declare const UniswapMagentaIcon: (props: SVGProps) => JSX.Element;
export {};
